---
title: 'Lab 4: Deep Learning - iNaturalist'
author: "Clarissa Boyajian"
date: "2/16/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

librarian::shelf(digest, tidyverse, tensorflow, keras)

# path to folder containing species directories of images
original_dataset_dir <- "/courses/EDS232/inaturalist-2021/train_mini"

# path to output table of paths, which could be read by R, eg read_csv()
inat_spp_dirs_csv <- "~/inat_species_dirs.csv" # I don't see this csv in taylor??

# get list of directories, one per species (n = 10,000 species)
dirs_spp <- list.dirs(original_dataset_dir, recursive = F)
n_spp <- length(dirs_spp) # 10,000 species directories

# set seed (for reproducible results) 
# just before sampling (otherwise get different results)
# based on your username (unique amongst class)
Sys.info()[["user"]] %>% 
  digest::digest2int() %>% 
  set.seed()
i10 <- sample(1:n_spp, 10)

# show the 10 indices sampled of the 10,000 possible 
i10

# show the 10 species directory names
species_10 <- basename(dirs_spp)[i10]
species_10
```

```{r}
# show the first 2 species directory names
i2 <- i10[1:2]
species_2 <- basename(dirs_spp)[i2]
species_2
```

## 2 species

```{r}
#original_dataset_dir <- "/courses/EDS232/inaturalist-2021/train_mini"

# create base file paths
base_dir <- "/Users/cboyajian/winter_quarter/EDS232/eds232_lab4_deep-learning"
train_2_dir <- file.path(base_dir, "train_2")
validation_2_dir <- file.path(base_dir, "validation_2")
test_2_dir <- file.path(base_dir, "test_2")
# create base folders (train, validate, test)
dir.create(train_2_dir)
dir.create(validation_2_dir)
dir.create(test_2_dir)

# create folder for both species
for (i in 1:length(species_2)){
  dir.create(file.path(train_2_dir, str_sub(species_2[[i]], start = 1, end = 5)))
  dir.create(file.path(validation_2_dir, str_sub(species_2[[i]], start = 1, end = 5)))
  dir.create(file.path(test_2_dir, str_sub(species_2[[i]], start = 1, end = 5)))
}
```

```{r}
# create test, validation, and training groups of images for both species
for(i in 1:length(species_2)){
  # create 5 groups of 10 random samples
  species_samples_2 <- replicate(5, 
                                  sample(list.files(paste0(original_dataset_dir, "/", species_2[[i]]), 
                                                    full.names = TRUE), replace = FALSE, 10))
  ## train n = 30 ##
  train <- rbind(species_samples_2[,1], species_samples_2[,2], species_samples_2[,3])
  file.copy(from = train, 
            to = paste0(train_2_dir, "/", str_sub(species_2[[i]], start = 1, end = 5)))
  ## validation n = 10 ##
  validate <- species_samples_2[,4]
  file.copy(from = validate,
            to = paste0(validation_2_dir, "/", str_sub(species_2[[i]], start = 1, end = 5)))
  ## train n = 10 ##
  test <- species_samples_2[,5]
  file.copy(from = test,
            to = paste0(test_2_dir, "/", str_sub(species_2[[i]], start = 1, end = 5)))
  }
```

```{r}
## pre-processing ##

## all images will be rescaled by 1/255 ##
train_datagen <- image_data_generator(rescale = 1/255)
validation_datagen <- image_data_generator(rescale = 1/255)

train_2_generator <- flow_images_from_directory(
  train_2_dir, # target directory
  train_datagen, # data generator
  target_size = c(150, 150), # all images resized to 150x150
  batch_size = 5, # larger than 5 throws error
  class_mode = "binary" # used binary_crossentropy loss, need binary labels
  )

validation_2_generator <- flow_images_from_directory(
  validation_2_dir,
  validation_datagen,
  target_size = c(150, 150),
  batch_size = 5,
  class_mode = "binary")
```

### neural net

```{r}
# model using neural nets
model_2 <- keras_model_sequential() %>% 
  layer_dense(units = 16, activation = "relu", input_shape = c(150, 150, 3)) %>%
  layer_flatten() %>% 
  layer_dense(units = 16, activation = "relu") %>% 
  layer_dense(units =  1, activation = "sigmoid") 
```

```{r}
# compiling model
model_2 %>% compile(
  loss = "binary_crossentropy",
  optimizer = optimizer_rmsprop(lr = 1e-4),
  metrics = c("acc"))
```

```{r}
# fitting model using neural nets
history_2 <- model_2 %>% fit_generator(
    train_2_generator,
    steps_per_epoch = 5,
    epochs = 30,
    validation_data = validation_2_generator,
    validation_steps = 5)
```

```{r}
plot(history_2)
```


### convolutional neural net

```{r}
# model using convolutional neural net
model_2_cnn <- keras_model_sequential() %>% 
  layer_conv_2d(filters = 32, kernel_size = c(3, 3), activation = "relu",
                input_shape = c(150, 150, 3)) %>% 
  layer_max_pooling_2d(pool_size = c(2, 2)) %>% 
  layer_conv_2d(filters = 64, kernel_size = c(3, 3), activation = "relu") %>% 
  layer_max_pooling_2d(pool_size = c(2, 2)) %>% 
  layer_conv_2d(filters = 128, kernel_size = c(3, 3), activation = "relu") %>% 
  layer_max_pooling_2d(pool_size = c(2, 2)) %>% 
  layer_conv_2d(filters = 128, kernel_size = c(3, 3), activation = "relu") %>% 
  layer_max_pooling_2d(pool_size = c(2, 2)) %>% 
  layer_flatten() %>% 
  layer_dense(units = 512, activation = "relu") %>% 
  layer_dense(units = 1, activation = "sigmoid")
```

```{r}
# compiling model cnn
model_2_cnn %>% compile(
  loss = "binary_crossentropy",
  optimizer = optimizer_rmsprop(lr = 1e-4),
  metrics = c("acc"))
```

```{r}
# fitting model cnn
history_2_cnn <- model_2_cnn %>% fit_generator(
    train_2_generator,
    steps_per_epoch = 5,
    epochs = 30,
    validation_data = validation_2_generator,
    validation_steps = 5)
```

```{r}
plot(history_2_cnn)
```




## 10 species

```{r}
#original_dataset_dir <- "/courses/EDS232/inaturalist-2021/train_mini"

# create base file paths
base_dir <- "/Users/cboyajian/winter_quarter/EDS232/eds232_lab4_deep-learning"
train_10_dir <- file.path(base_dir, "train_10")
validation_10_dir <- file.path(base_dir, "validation_10")
test_10_dir <- file.path(base_dir, "test_10")
# create base folders (train, validate, test)
dir.create(train_10_dir)
dir.create(validation_10_dir)
dir.create(test_10_dir)

# create folder for all 10 species
for (i in 1:length(species_10)){
  dir.create(file.path(train_10_dir, str_sub(species_10[[i]], start = 1, end = 5)))
  dir.create(file.path(validation_10_dir, str_sub(species_10[[i]], start = 1, end = 5)))
  dir.create(file.path(test_10_dir, str_sub(species_10[[i]], start = 1, end = 5)))
}
```


```{r}
# create test, validation, and training groups of images
for(i in 1:length(species_10)){
  # create 5 groups of 10 random samples
  species_samples_10 <- replicate(5, 
                                  sample(list.files(paste0(original_dataset_dir, "/", species_10[[i]]), 
                                                    full.names = TRUE), replace = FALSE, 10))
  ## train n = 30 ##
  train <- rbind(species_samples_10[,1], species_samples_10[,2], species_samples_10[,3])
  file.copy(from = train, 
            to = paste0(train_10_dir, "/", str_sub(species_10[[i]], start = 1, end = 5)))
  ## validation n = 10 ##
  validate <- species_samples_10[,4]
  file.copy(from = validate,
            to = paste0(validation_10_dir, "/", str_sub(species_10[[i]], start = 1, end = 5)))
  ## train n = 10 ##
  test <- species_samples_10[,5]
  file.copy(from = test,
            to = paste0(test_10_dir, "/", str_sub(species_10[[i]], start = 1, end = 5)))
  }
```





